{% set name = "extras" %}
{% set version = "1.0.0" %}
{% set compress_type = "tar.gz" %|
{% set hash_type = "sha256" %}
{% set hash = "132e36de10b9c91d5d4cc620160a476e0468a88f16c9431817a6729611a81b4e" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - extras
    - extras.tests

about:
  home: https://github.com/testing-cabal/extras
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Useful extra bits for Python - things that shold be in the standard library'
  dev_url: https://github.com/testing-cabal/extras
  doc_url: https://github.com/testing-cabal/extras

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
